[project]
name = "dasmixer-gui"
version = "0.7.2a3"
description = "DASMixer GUI — Flet-based desktop application"
authors = [
    {name = "gluck", email = "glucksistemi@gmail.com"}
]
readme = "README.md"
requires-python = "<4.0, >=3.11"
urls = {Homepage = "https://github.com/protdb/dasmixer"}
dependencies = [
    "dasmixer-core[all] ==0.7.2a3",
    "flet[all] >=0.80.4,<0.81.0",
    "pywebview[gtk] >=6.1,<7 ; sys_platform == 'linux'",
    "pywebview >=6.1,<7 ; sys_platform == 'win32'",
    "pythonnet ==3.1.0rc0 ; sys_platform == 'win32' and python_version >= '3.14' and python_version < '3.15'",
    "pythonnet ==3.0.5 ; sys_platform == 'win32' and python_version < '3.14'",
]

[project.scripts]
dasmixer = "dasmixer.gui.main:app"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    {include = "dasmixer/gui", from = "src"},
]
include = ["src/dasmixer/gui/assets/**/*"]

[tool.poetry.dependencies]
dasmixer-core = {path = "../dasmixer-core", develop = true}
pythonnet = [
    {version = "==3.1.0rc0", python = ">=3.14,<3.15", markers = "sys_platform == 'win32'", allow-prereleases = true},
    {version = "==3.0.5", python = ">=3.11,<3.14", markers = "sys_platform == 'win32'"},
]
